<a href="https://colab.research.google.com/github/GodishalaAshwith/LearningTensorFlow/blob/main/TensorFlowIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

##Basics

### Creating a Tensor

In [ ]:
#Constants
scalar = tf.constant(5)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])

#Variables
variable = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

#Random Values
random_tensor = tf.random.uniform(shape=(2, 3), minval=0, maxval=10, dtype=tf.int32)

In [ ]:
# Creating a 2x3 matrix tensor
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Tensor:\n", matrix)
print("Shape:", matrix.shape)
print("Data Type:", matrix.dtype)
print("Rank:", tf.rank(matrix).numpy())

Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)
Data Type: <dtype: 'int32'>
Rank: 2


### Manipulating Tensor Shapes

In [ ]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Original tensor:\n", matrix)

# Reshape
reshaped = tf.reshape(matrix, shape=(3, 2))
print("\nReshaped tensor (3x2):\n", reshaped)

# Expand Dimensions
expanded = tf.expand_dims(matrix, axis=0)
print("\nExpanded tensor (added axis at the beginning):\n", expanded)

# Squeeze Dimensions (demonstrate with a tensor that has a dimension of size 1)
single_dim_tensor = tf.constant([[[1], [2], [3]]])
print("\nOriginal tensor with single dimension:\n", single_dim_tensor)
squeezed = tf.squeeze(single_dim_tensor, axis=2)
print("\nSqueezed tensor (removed axis of size 1):\n", squeezed)

# Transpose
transposed = tf.transpose(matrix, perm=[1, 0]) # Transposing a 2x3 matrix results in a 3x2 matrix
print("\nTransposed tensor:\n", transposed)

Original tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Reshaped tensor (3x2):
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

Expanded tensor (added axis at the beginning):
 tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)

Original tensor with single dimension:
 tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)

Squeezed tensor (removed axis of size 1):
 tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)

Transposed tensor:
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


###Specifying Datatype

In [ ]:
import tensorflow as tf

# Creating a tensor with a specific data type
float_tensor = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
bool_tensor = tf.constant([True, False, True], dtype=tf.bool)

###Type Casting

In [ ]:
# Casting float tensor to int tensor
print(float_tensor)
casted_tensor = tf.cast(float_tensor, dtype=tf.int32)
print(casted_tensor)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


### Next