<a href="https://colab.research.google.com/github/GodishalaAshwith/LearningTensorFlow/blob/main/TensorFlowIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

##Basics

### Creating a Tensor

In [ ]:
#Constants
scalar = tf.constant(5)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])

#Variables
variable = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

#Random Values
random_tensor = tf.random.uniform(shape=(2, 3), minval=0, maxval=10, dtype=tf.int32)

In [ ]:
# Creating a 2x3 matrix tensor
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Tensor:\n", matrix)
print("Shape:", matrix.shape)
print("Data Type:", matrix.dtype)
print("Rank:", tf.rank(matrix).numpy())

Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)
Data Type: <dtype: 'int32'>
Rank: 2


### Manipulating Tensor Shapes

In [ ]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Original tensor:\n", matrix)

# Reshape
reshaped = tf.reshape(matrix, shape=(3, 2))
print("\nReshaped tensor (3x2):\n", reshaped)

# Expand Dimensions
expanded = tf.expand_dims(matrix, axis=0)
print("\nExpanded tensor (added axis at the beginning):\n", expanded)

# Squeeze Dimensions (demonstrate with a tensor that has a dimension of size 1)
single_dim_tensor = tf.constant([[[1], [2], [3]]])
print("\nOriginal tensor with single dimension:\n", single_dim_tensor)
squeezed = tf.squeeze(single_dim_tensor, axis=2)
print("\nSqueezed tensor (removed axis of size 1):\n", squeezed)

# Transpose
transposed = tf.transpose(matrix, perm=[1, 0]) # Transposing a 2x3 matrix results in a 3x2 matrix
print("\nTransposed tensor:\n", transposed)

Original tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Reshaped tensor (3x2):
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

Expanded tensor (added axis at the beginning):
 tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)

Original tensor with single dimension:
 tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)

Squeezed tensor (removed axis of size 1):
 tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)

Transposed tensor:
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


###Specifying Datatype

In [ ]:
import tensorflow as tf

# Creating a tensor with a specific data type
float_tensor = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
bool_tensor = tf.constant([True, False, True], dtype=tf.bool)

###Type Casting

In [ ]:
# Casting float tensor to int tensor
print(float_tensor)
casted_tensor = tf.cast(float_tensor, dtype=tf.int32)
print(casted_tensor)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


## Basic Tensor Operations

###Element Wise Operations

In [ ]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

#Addition
c = tf.add(a,b) # or c = a + b
print("Addition:",c.numpy())

c = tf.subtract(a,b) # or c = a - b
print("Subtraction:",c.numpy())

c = tf.multiply(a,b) # or c = a * b
print("Multiplication:",c.numpy())

c = tf.divide(b,a) # or c = b / a
print("Division:",c.numpy())

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


###Matrix Operations

In [ ]:
m1 = tf.constant([[1,2],[3,4]])
m2 = tf.constant([[5,6],[7,8]])

#Matrix multiplication
prod = tf.matmul(m1,m2)
print(f"Matrix Multiplication: {prod}")

#Transpose of a Matrix
t = tf.transpose(m1)
print(f"Transpose of Matrix: {t}")

Matrix Multiplication: [[19 22]
 [43 50]]
Transpose of Matrix: [[1 3]
 [2 4]]


###Slicing and Indexing

In [ ]:
# Creating a 3-D tensor
tensor = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

# Slicing the first two matrices
sliced = tensor[:2]
print("Sliced Tensor:\n", sliced.numpy())

# Accessing a specific element
element = tensor[1, 1, 1]
print("Specific Element:", element.numpy())  # Output: 8

Sliced Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Specific Element: 8


###Broadcasting

In [ ]:
# Tensor A of shape (3, 1)
A = tf.constant([[1], [2], [3]])

# Tensor B of shape (1, 4)
B = tf.constant([[10, 20, 30, 40]])

# Broadcasting to shape (3, 4)
C = A + B
print("Broadcasted Tensor:\n", C.numpy())

Broadcasted Tensor:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


###Reduction Operations

In [ ]:
tensor = tf.constant([[1, 2], [3, 4]])

#Sum
sum_all = tf.reduce_sum(tensor)           # 10
sum_axis0 = tf.reduce_sum(tensor, axis=0) # [4, 6]
sum_axis1 = tf.reduce_sum(tensor, axis=1) # [3, 7]

#Mean
mean_all = tf.reduce_mean(tensor)         # 2.5
mean_axis0 = tf.reduce_mean(tensor,axis=0)# [2 3]
mean_axis1 = tf.reduce_mean(tensor,axis=1)# [1 3]

#Maximum
max_all = tf.reduce_max(tensor)           # 4
max_axis0 = tf.reduce_max(tensor,axis=0)  # [3 4]
max_axis1 = tf.reduce_max(tensor,axis=1)  # [2 4]

#Minimum
min_all = tf.reduce_min(tensor)           # 1
min_axis0 = tf.reduce_min(tensor,axis=0)  # [1 2]
min_axis1 = tf.reduce_min(tensor,axis=1)  # [1 3]

###Concatenating n Stacking

In [ ]:
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

# Concatenate along axis 0
concat_axis0 = tf.concat([tensor1, tensor2], axis=0)
print("Concatenated along axis 0:\n", concat_axis0.numpy())

# Concatenate along axis 1
concat_axis1 = tf.concat([tensor1, tensor2], axis=1)
print("Concatenated along axis 1:\n", concat_axis1.numpy())

# Stack tensors along a new axis
stacked = tf.stack([tensor1, tensor2], axis=0)
print("Stacked Tensor:\n", stacked.numpy())
print("Stacked Shape:", stacked.shape)  # (2, 2, 2)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]
Stacked Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Stacked Shape: (2, 2, 2)


###Advanced Operations

One-Hot Encoding (tf.one_hot):

In [ ]:
indices = tf.constant([0, 1, 2, 1])
depth = 3
one_hot = tf.one_hot(indices, depth)
print("One-Hot Encoded Tensor:\n", one_hot.numpy())

One-Hot Encoded Tensor:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


Matrix Inversion (tf.linalg.inv):

In [ ]:
matrix = tf.constant([[1., 2.], [3., 4.]])
inverse = tf.linalg.inv(matrix)
print("Inverse of Matrix:\n", inverse.numpy())

Inverse of Matrix:
 [[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]


Eigenvalues and Eigenvectors (tf.linalg.eig):

In [ ]:
matrix = tf.constant([[1., 2.], [3., 4.]])
eigenvalues, eigenvectors = tf.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues.numpy())
print("Eigenvectors:\n", eigenvectors.numpy())

Eigenvalues: [-0.37228122+0.j  5.372281  +0.j]
Eigenvectors:
 [[-0.8245648 +0.j -0.41597357+0.j]
 [ 0.56576747+0.j -0.90937674+0.j]]


##Computational Graphs

###Static Computational Graphs